name: tests

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.12.0
        python-version:
          - 3.7
          - 3.8
          - 3.9

    steps:
      - name: Checkout Python code
        uses: actions/checkout@v2

      - name: Set up private ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Checkout OCaml facile library
        run: |
          ssh-keyscan git.recherche.enac.fr > ~/.ssh/known_hosts
          git clone git@git.recherche.enac.fr:facile.git facile.ml
          cd facile.ml
          git checkout 03a93f9

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.6
          virtualenvs-in-project: true

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          # ocaml-compiler: ${{ matrix.ocaml-compiler }}
          ocaml-compiler: 4.04.2+fPIC

      - name: Switch to most recent +fPIC variant (Ubuntu only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          OPAM_SWITCH=4.04.2+fPIC
          echo 'OPAM_SWITCH=$OPAM_SWITCH' >> $GITHUB_ENV
          opam switch create ${{ env.OPAM_SWITCH }}
          opam switch ${{ env.OPAM_SWITCH }}

      - name: Switch to msvc64 variant (Windows only)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          OPAM_SWITCH=4.11.0+msvc64
          echo 'OPAM_SWITCH=$OPAM_SWITCH' >> $GITHUB_ENV
          opam switch create ${{ env.OPAM_SWITCH }}
          opam switch ${{ env.OPAM_SWITCH }}

      - name: Compile and install facile.ml library (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        working-directory: ./facile.ml
        run: |
          opam install ocamlfind ocamlbuild
          opam exec -- make
          opam exec -- make install

      - name: Compile and install facile.ml library (Windows)
        if: ${{ matrix.os != 'macos-latest' }}
        working-directory: ./facile.ml
        run: |
          opam install --switch=${{ env.OPAM_SWITCH }} ocamlfind ocamlbuild
          opam exec --switch=${{ env.OPAM_SWITCH }} -- make
          opam exec --switch=${{ env.OPAM_SWITCH }} -- make install

      - name: Install Python facile library (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          opam exec -- poetry install

      - name: Install Python facile library (Ubuntu and Windows)
        if: ${{ matrix.os != 'macos-latest' }}
        run: |
          eval $(opam env --set-switch --switch=${{ env.OPAM_SWITCH }})
          opam exec -- poetry install

      - name: tmate session if tests fail
        if: failure() && matrix.python-version == 3.9
        uses: mxschmitt/action-tmate@v3

      - name: Style checking
        run: |
          poetry run flake8 facile examples tests
          poetry run isort --check-only facile examples tests
          poetry run black --check facile examples tests

      - name: Type checking
        run: |
          poetry run mypy facile examples tests

      - name: Run Pytest
        run: |
          poetry run pytest

      - name: Build wheel
        run: |
          poetry build

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}-facile-wheel
          path: dist/*.whl
